-- ============================================================
--  APEX Finance Dashboard — Esquema de base de datos (Supabase)
-- ============================================================
--  Proyecto: lkndwsolpimmezdshgpx.supabase.co
--
--  DDL reconstruido a partir del uso que hace js/app.js de Supabase
--  (tabla `expenses`, bucket `vouchers`, auth + RLS).
--
--  IDEMPOTENTE: puedes ejecutarlo las veces que quieras sin errores.
--  Para las políticas RLS primero ELIMINA cualquier política previa
--  de `expenses` (incluida "Own read") y luego recrea un set canónico
--  equivalente. El comportamiento de seguridad es el mismo: cada
--  usuario sólo ve/gestiona sus propios gastos.
-- ============================================================

-- ------------------------------------------------------------
--  1) Tabla: expenses
-- ------------------------------------------------------------
create table if not exists public.expenses (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null default auth.uid()
                          references auth.users (id) on delete cascade,
  concept     text        not null,
  amount      numeric(12, 2) not null check (amount >= 0),
  currency    text        not null default 'USD' check (currency in ('USD', 'PEN')),
  date        date        not null,
  time        time        not null,
  image_url   text,                       -- URL canónica del voucher (bucket privado; la app la firma al verlo). Opcional.
  created_at  timestamptz not null default now()
);

-- Añade `currency` si la tabla ya existía sin esa columna (create table
-- se salta si ya existe). USD = Dólares, PEN = Soles.
alter table public.expenses
  add column if not exists currency text not null default 'USD'
  check (currency in ('USD', 'PEN'));

-- Asegura el default AUNQUE la tabla ya existiera de antes (create table
-- se salta si ya existe, por lo que el default de arriba no se aplicaría).
-- Sin esto, un insert sin user_id lo deja en NULL y RLS bloquea la fila.
alter table public.expenses
  alter column user_id set default auth.uid();

create index if not exists expenses_user_id_idx on public.expenses (user_id);
create index if not exists expenses_date_idx    on public.expenses (date desc);
create index if not exists expenses_user_id_date_time_idx on public.expenses (user_id, date desc, time desc);

-- ------------------------------------------------------------
--  2) Row Level Security
-- ------------------------------------------------------------
alter table public.expenses enable row level security;

-- Elimina TODAS las políticas existentes de expenses (cualquier nombre)
do $$
declare
  pol record;
begin
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'expenses'
  loop
    execute format('drop policy %I on public.expenses', pol.policyname);
  end loop;
end $$;

-- Recrea el set canónico (cada usuario sólo accede a lo suyo).
-- `(select auth.uid())` en vez de `auth.uid()`: se evalúa una sola vez por
-- consulta y no por fila (advisor de performance `auth_rls_initplan`).
create policy "expenses_select_own"
  on public.expenses for select
  using ((select auth.uid()) = user_id);

create policy "expenses_insert_own"
  on public.expenses for insert
  with check ((select auth.uid()) = user_id);

create policy "expenses_update_own"
  on public.expenses for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "expenses_delete_own"
  on public.expenses for delete
  using ((select auth.uid()) = user_id);


-- ============================================================
--  3) Storage: bucket `vouchers` (PRIVADO)
-- ============================================================
--  Los vouchers son datos financieros sensibles: el bucket es PRIVADO y la
--  app los muestra con URLs firmadas temporales (createSignedUrl).
--  Además se limita el contenido a imágenes rasterizadas de máx 5MB
--  (nada de SVG/HTML, que pueden ejecutar scripts al servirse).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('vouchers', 'vouchers', false, 5242880, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ------------------------------------------------------------
--  Políticas de Storage (idempotentes y a prueba de transacción)
--
--  IMPORTANTE: en algunos proyectos crear políticas sobre
--  storage.objects requiere ser owner y falla con
--      ERROR: 42501: must be owner of table objects
--  El SQL Editor corre TODO en una transacción, así que ese error
--  revertiría también las políticas de `expenses` de arriba.
--
--  Por eso van dentro de un bloque que CAPTURA el error de permisos:
--  si no se pueden crear por SQL, el script continúa y tú las creas
--  desde el panel: Storage → vouchers → Policies → New policy
--  (borra antes las políticas viejas del bucket, incluidas las de
--  sufijo raro tipo "vouchers_auth_delete 183bix1_1"):
--    • SELECT · authenticated · USING:      bucket_id = 'vouchers' and (storage.foldername(name))[1] = (select auth.uid())::text
--    • INSERT · authenticated · WITH CHECK: bucket_id = 'vouchers' and (storage.foldername(name))[1] = (select auth.uid())::text
--    • DELETE · authenticated · USING:      bucket_id = 'vouchers' and (storage.foldername(name))[1] = (select auth.uid())::text
-- ------------------------------------------------------------
do $$
declare
  pol record;
begin
  -- Elimina TODAS las políticas previas del bucket (cualquier nombre que
  -- empiece por "vouchers", incluidas las creadas desde el panel).
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname like 'vouchers%'
  loop
    execute format('drop policy %I on storage.objects', pol.policyname);
  end loop;

  -- Cada usuario sólo ve/sube/borra archivos de SU carpeta (<user_id>/...)
  create policy "vouchers_select_own"
    on storage.objects for select
    to authenticated
    using (bucket_id = 'vouchers' and (storage.foldername(name))[1] = (select auth.uid())::text);

  create policy "vouchers_insert_own"
    on storage.objects for insert
    to authenticated
    with check (bucket_id = 'vouchers' and (storage.foldername(name))[1] = (select auth.uid())::text);

  create policy "vouchers_delete_own"
    on storage.objects for delete
    to authenticated
    using (bucket_id = 'vouchers' and (storage.foldername(name))[1] = (select auth.uid())::text);
exception
  when insufficient_privilege then
    raise notice 'No se pudieron crear las políticas de storage por SQL (must be owner). Créalas desde el panel: Storage → vouchers → Policies.';
end $$;


-- ============================================================
--  4) Categorización y Presupuestos (Actualización 2026-06-18)
-- ============================================================

-- Columna de categoría en expenses
alter table public.expenses
  add column if not exists category text not null default 'Otros';

-- Tabla para almacenar límites de presupuesto mensual por usuario y moneda
create table if not exists public.budgets (
  id          uuid not null default gen_random_uuid() primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  currency    text not null check (currency in ('USD', 'PEN')),
  amount      numeric(10, 2) not null check (amount >= 0),
  created_at  timestamptz not null default now(),
  constraint unique_user_currency unique (user_id, currency)
);

-- Habilitar Row Level Security (RLS) en budgets
alter table public.budgets enable row level security;

-- Eliminar políticas previas si existen de budgets
do $$
declare
  pol record;
begin
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'budgets'
  loop
    execute format('drop policy %I on public.budgets', pol.policyname);
  end loop;
end $$;

-- Crear política RLS para budgets (acceso completo a los propios presupuestos)
create policy "budgets_manage_own"
  on public.budgets for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);


-- ============================================================
--  4.2) Endurecimiento de expenses (mejoras 2026-07-03)
-- ============================================================
--  Espeja en el servidor las validaciones que el cliente hace en
--  js/utils.js (validateExpenseInput): el cliente puede saltarse el JS,
--  la base de datos no.
alter table public.expenses drop constraint if exists expenses_category_check;
alter table public.expenses
  add constraint expenses_category_check
  check (category in ('Alimentación', 'Transporte', 'Servicios', 'Suscripciones', 'Oficina', 'Otros'));

alter table public.expenses drop constraint if exists expenses_concept_len_check;
alter table public.expenses
  add constraint expenses_concept_len_check
  check (char_length(concept) between 1 and 200);

alter table public.expenses drop constraint if exists expenses_amount_max_check;
alter table public.expenses
  add constraint expenses_amount_max_check
  check (amount <= 1000000);

-- Auditoría de cambios: updated_at se refresca solo en cada UPDATE.
alter table public.expenses
  add column if not exists updated_at timestamptz not null default now();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists expenses_set_updated_at on public.expenses;
create trigger expenses_set_updated_at
  before update on public.expenses
  for each row execute function public.set_updated_at();


-- ============================================================
--  4.3) RPC: dashboard_summary — KPIs calculados en SQL
-- ============================================================
--  Devuelve en una sola llamada los agregados que el dashboard necesita,
--  exactos aunque haya millones de filas (el cliente ya no depende de
--  traerse los gastos para sumar). Recibe las fechas del CLIENTE porque
--  "hoy" y el inicio de semana dependen de su zona horaria, no de la del
--  servidor (UTC).
--
--  SECURITY INVOKER (default): corre como el usuario autenticado, así que
--  RLS aplica; el filtro explícito por user_id es defensa en profundidad.
create or replace function public.dashboard_summary(p_today date, p_week_start date)
returns jsonb
language sql
stable
set search_path = ''
as $$
  with mine as (
    select date, currency, amount, category
    from public.expenses
    where user_id = (select auth.uid())
  ),
  month as (
    select *
    from mine
    where date >= date_trunc('month', p_today)::date
      and date <  (date_trunc('month', p_today) + interval '1 month')::date
  )
  select jsonb_build_object(
    'daily', (
      select coalesce(jsonb_object_agg(currency, total), '{}'::jsonb)
      from (select currency, sum(amount) as total from mine where date = p_today group by currency) d
    ),
    'weekly', (
      select coalesce(jsonb_object_agg(currency, total), '{}'::jsonb)
      from (select currency, sum(amount) as total from mine where date between p_week_start and p_today group by currency) w
    ),
    'monthly', (
      select coalesce(jsonb_object_agg(currency, total), '{}'::jsonb)
      from (select currency, sum(amount) as total from month group by currency) m
    ),
    'by_date', (
      select coalesce(jsonb_agg(jsonb_build_object('date', date, 'currency', currency, 'total', total) order by date), '[]'::jsonb)
      from (select date, currency, sum(amount) as total from month group by date, currency) s
    ),
    'by_category', (
      select coalesce(jsonb_agg(jsonb_build_object('category', category, 'currency', currency, 'total', total)), '[]'::jsonb)
      from (select category, currency, sum(amount) as total from month group by category, currency) c
    )
  );
$$;

revoke execute on function public.dashboard_summary(date, date) from anon, public;
grant execute on function public.dashboard_summary(date, date) to authenticated;


-- ============================================================
--  4.4) GRANTs para la API (rol `authenticated`)
-- ============================================================
--  PostgREST entra con los roles `anon` / `authenticated`. RLS filtra QUÉ
--  filas se ven, pero primero hace falta GRANT para acceder a la TABLA; sin
--  esto la API devuelve: "permission denied for table budgets".
--
--  Las tablas creadas desde la UI de Supabase reciben estos GRANTs
--  automáticamente; las creadas por SQL (como `budgets`) NO, por eso hay que
--  otorgarlos explícitamente aquí. RLS sigue protegiendo cada fila.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.expenses to authenticated;
grant select, insert, update, delete on public.budgets  to authenticated;


-- ============================================================
--  5) Recargar el caché de esquema de PostgREST
-- ============================================================
--  Tras añadir columnas (p. ej. `category`), la API REST de Supabase puede
--  seguir usando un esquema cacheado y devolver:
--    "Could not find the 'category' column of 'expenses' in the schema cache"
--  Este NOTIFY fuerza la recarga inmediata del esquema.
notify pgrst, 'reload schema';

