-- ============================================================
--  APEX Finance Dashboard — Esquema de base de datos (Supabase)
-- ============================================================
--  Proyecto: lkndwsolpimmezdshgpx.supabase.co
--
--  DDL reconstruido a partir del uso que hace js/app.js de Supabase
--  (tabla `expenses`, bucket `vouchers`, auth + RLS).
--
--  IDEMPOTENTE: puedes ejecutarlo las veces que quieras sin errores.
--  Para las políticas RLS primero ELIMINA cualquier política previa
--  de `expenses` (incluida "Own read") y luego recrea un set canónico
--  equivalente. El comportamiento de seguridad es el mismo: cada
--  usuario sólo ve/gestiona sus propios gastos.
-- ============================================================

-- ------------------------------------------------------------
--  1) Tabla: expenses
-- ------------------------------------------------------------
create table if not exists public.expenses (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null default auth.uid()
                          references auth.users (id) on delete cascade,
  concept     text        not null,
  amount      numeric(12, 2) not null check (amount >= 0),
  currency    text        not null default 'USD' check (currency in ('USD', 'PEN')),
  date        date        not null,
  time        time        not null,
  image_url   text,                       -- URL pública del voucher (Storage). Opcional.
  created_at  timestamptz not null default now()
);

-- Añade `currency` si la tabla ya existía sin esa columna (create table
-- se salta si ya existe). USD = Dólares, PEN = Soles.
alter table public.expenses
  add column if not exists currency text not null default 'USD'
  check (currency in ('USD', 'PEN'));

-- Asegura el default AUNQUE la tabla ya existiera de antes (create table
-- se salta si ya existe, por lo que el default de arriba no se aplicaría).
-- Sin esto, un insert sin user_id lo deja en NULL y RLS bloquea la fila.
alter table public.expenses
  alter column user_id set default auth.uid();

create index if not exists expenses_user_id_idx on public.expenses (user_id);
create index if not exists expenses_date_idx    on public.expenses (date desc);
create index if not exists expenses_user_id_date_time_idx on public.expenses (user_id, date desc, time desc);

-- ------------------------------------------------------------
--  2) Row Level Security
-- ------------------------------------------------------------
alter table public.expenses enable row level security;

-- Elimina TODAS las políticas existentes de expenses (cualquier nombre)
do $$
declare
  pol record;
begin
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'expenses'
  loop
    execute format('drop policy %I on public.expenses', pol.policyname);
  end loop;
end $$;

-- Recrea el set canónico (cada usuario sólo accede a lo suyo)
create policy "expenses_select_own"
  on public.expenses for select
  using (auth.uid() = user_id);

create policy "expenses_insert_own"
  on public.expenses for insert
  with check (auth.uid() = user_id);

create policy "expenses_update_own"
  on public.expenses for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "expenses_delete_own"
  on public.expenses for delete
  using (auth.uid() = user_id);


-- ============================================================
--  3) Storage: bucket `vouchers`
-- ============================================================
--  Crear el bucket SIEMPRE funciona en el SQL Editor:
insert into storage.buckets (id, name, public)
values ('vouchers', 'vouchers', true)
on conflict (id) do nothing;

-- ------------------------------------------------------------
--  Políticas de Storage (idempotentes y a prueba de transacción)
--
--  IMPORTANTE: en algunos proyectos crear políticas sobre
--  storage.objects requiere ser owner y falla con
--      ERROR: 42501: must be owner of table objects
--  El SQL Editor corre TODO en una transacción, así que ese error
--  revertiría también las políticas de `expenses` de arriba.
--
--  Por eso van dentro de un bloque que CAPTURA el error de permisos:
--  si no se pueden crear por SQL, el script continúa y tú las creas
--  desde el panel: Storage → vouchers → Policies → New policy
--    • SELECT  · roles: public          · USING:      bucket_id = 'vouchers'
--    • INSERT  · roles: authenticated    · WITH CHECK: bucket_id = 'vouchers'
--    • DELETE  · roles: authenticated    · USING:      bucket_id = 'vouchers'
-- ------------------------------------------------------------
do $$
begin
  drop policy if exists "vouchers_public_read" on storage.objects;
  create policy "vouchers_public_read"
    on storage.objects for select
    using (bucket_id = 'vouchers');

  drop policy if exists "vouchers_auth_insert" on storage.objects;
  create policy "vouchers_auth_insert"
    on storage.objects for insert
    to authenticated
    with check (bucket_id = 'vouchers' and (storage.foldername(name))[1] = auth.uid()::text);

  drop policy if exists "vouchers_auth_delete" on storage.objects;
  create policy "vouchers_auth_delete"
    on storage.objects for delete
    to authenticated
    using (bucket_id = 'vouchers' and (storage.foldername(name))[1] = auth.uid()::text);
exception
  when insufficient_privilege then
    raise notice 'No se pudieron crear las políticas de storage por SQL (must be owner). Créalas desde el panel: Storage → vouchers → Policies.';
end $$;


-- ============================================================
--  4) Categorización y Presupuestos (Actualización 2026-06-18)
-- ============================================================

-- Columna de categoría en expenses
alter table public.expenses
  add column if not exists category text not null default 'Otros';

-- Tabla para almacenar límites de presupuesto mensual por usuario y moneda
create table if not exists public.budgets (
  id          uuid not null default gen_random_uuid() primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  currency    text not null check (currency in ('USD', 'PEN')),
  amount      numeric(10, 2) not null check (amount >= 0),
  created_at  timestamptz not null default now(),
  constraint unique_user_currency unique (user_id, currency)
);

-- Habilitar Row Level Security (RLS) en budgets
alter table public.budgets enable row level security;

-- Eliminar políticas previas si existen de budgets
do $$
declare
  pol record;
begin
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'budgets'
  loop
    execute format('drop policy %I on public.budgets', pol.policyname);
  end loop;
end $$;

-- Crear política RLS para budgets (acceso completo a los propios presupuestos)
create policy "budgets_manage_own"
  on public.budgets for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

